# Generated by Django 4.0.5 on 2022-06-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_alter_drivefile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivefile',
            old_name='social',
            new_name='social_user',
        ),
    ]
