# Generated by Django 4.0.5 on 2022-06-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0003_rename_social_drivefile_social_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
