# Generated by Django 4.0.5 on 2022-06-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0004_drivefile_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivefile',
            name='processed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
