# Generated by Django 4.0.5 on 2022-06-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0005_drivefile_processed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivefile',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='drivefile',
            name='trashed',
        ),
    ]
