# Generated by Django 4.0.5 on 2022-07-02 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drive', '0007_actionrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionrecord',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.drivefile'),
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='social_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount'),
        ),
        migrations.AlterField(
            model_name='drivefile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
